### ISSUE TITLE
edit invoice to add usage charges

### ISSUE THREAD

**Issue by deewali** [sudiptochoudhury/php-zoho-subscriptions#1]
Hi

How can I edit a pending invoice to set the usage charges of month.
I believe the following end point should be used but not able to find it on this package.
https://subscriptions.zoho.com/api/v1/invoices/{invoice_id}/lineitems

**Comment by sudiptochoudhury** [comment]
@deewali You are right. Thanks for reporting. It's one of the missing items from the endpoint definition. Will be added soon.

**Comment by sudiptochoudhury** [comment]
Released
