### ISSUE TITLE
Composer issue on dependency on linux

### ISSUE THREAD

**Issue by mircobabini** [sudiptochoudhury/php-zoho-subscriptions#5]
Hey, I've tried almost everything but I'm having an issue with your dependency.

On Mac Catalina php7.3 just works.
On Linux (tried CentOs7 and CloudLinux) php7.3 I'm facing this issue:

Fatal error: Class 'SudiptoChoudhury\Support\Forge\Api\Client' not found in /vendor/sudiptochoudhury/php-zoho-subscriptions/src/Zoho/Subscriptions/Api.php on line 186

Really can't say why, seems like a composer misconfiguration (?).
composer 1.10.5 but also tried 1.8.x.
same issue.

**Comment by sudiptochoudhury** [comment]
Hi,

I have pushed a change with possible fix based on PSR-4 Autoloading specs in the Api Forge package (`sudiptochoudhury/php-api-client-forge`). You may need to run `composer update sudiptochoudhury/php-api-client-forge`.
Please update, check and let me know.

**Comment by mircobabini** [comment]
Thanks for your time 🙏🏼 There is still another issue, I forgot to report earlier:

```
me@mine [~/test]# composer require sudiptochoudhury/php-zoho-subscriptions

Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2.0 is now available and you should upgrade. See https://getcomposer.org/2
Using version ^0.2.3 for sudiptochoudhury/php-zoho-subscriptions
./composer.json has been created
Loading composer repositories with package information
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2.0 is now available and you should upgrade. See https://getcomposer.org/2
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for sudiptochoudhury/php-zoho-subscriptions ^0.2.3 -> satisfiable by sudiptochoudhury/php-zoho-subscriptions[v0.2.3].
    - sudiptochoudhury/php-zoho-subscriptions v0.2.3 requires sudiptochoudhury/php-api-client-forge dev-master -> satisfiable by sudiptochoudhury/php-api-client-forge[dev-master] but these conflict with your requirements or minimum-stability.


Installation failed, deleting ./composer.json.
me@mine [~/test]#
```

**Comment by sudiptochoudhury** [comment]
Hi @mircobabini ,

Please check https://webtips.krajee.com/wp-content/cache/page_enhanced/webtips.krajee.com/setting-composer-minimum-stability-application/_index.html_gzip if it helps.

**Comment by mircobabini** [comment]
Yeah, thanks. It worked setting the minimum stability to dev:

```
{
  "name": "mycompany/myproject",
  "type": "project",
  "minimum-stability": "dev",
  "require": {
    "sudiptochoudhury/php-zoho-subscriptions": "dev-master"
  }
}
```
