### ISSUE TITLE
Header oauth token was change

### ISSUE THREAD

**Issue by MadDevPro** [sudiptochoudhury/php-zoho-subscriptions#7]
Hi ! 
I little fix is needed with the last version of Zoho Api.

`'client' => [
                'headers' => [
                    'Authorization' => 'Zoho-oauthtoken {{oauthtoken}}',`

**Zoho-authtoken** become **Zoho-oauthtoken**

Thanks :)

**Comment by sudiptochoudhury** [comment]
Hi
Will it be ok if you send a pull request with the desired changes?

**Comment by sudiptochoudhury** [comment]
Hi,

Happy to let you know that I have released a version `v0.3.0` that supports Zoho OAuthToken.
