### ISSUE TITLE
Folder names doesn't comply with PSR-4 

### ISSUE THREAD

**Issue by kudesnic** [sudiptochoudhury/php-zoho-subscriptions#8]
Version v0.2.3 has folder names Without capital letters. So it doesn't comply with PSR-4. It leads to errors such as class doesnt exist at namespace .... 
But the main branch has proper names of folders. Probably a new tag should be created

Thank you for the great package, it saved days for me!

**Comment by sudiptochoudhury** [comment]
Hi 
Will it be ok if you send a pull request with the changes?

**Comment by sudiptochoudhury** [comment]
Hi,

Apologies. I missed you point. I have released it.
